config/routes.rb
Rails.application.routes.draw do

  resources :testimonials

  resources :static_page, only: 'static_page#autocomplete' do
    collection do
      get 'autocomplete'
    end
  end

  # match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/:provider/callback', to: 'static_page#testimonial_user', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  match 'find_guest', to: 'static_page#find_guest', via: :post
  match 'confirm_guest', to: 'static_page#confirm_guest', via: :post
  match 'create_testimonial', to: 'static_page#create_testimonial', via: :post

  get '/new_testimonial', to: 'static_page#new_testimonial', as: 'new_testimonial_lightobx'

  root 'static_page#index'
end

app/models/guest.rb
class Guest < ActiveRecord::Base

  def self.find_by_name(name)
    where(Guest.arel_table[:name].matches("%#{name}%")).first
  end
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid).permit!).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.picture = auth.info.image
      user.profile_link = auth.extra.raw_info.link
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.from_omniauth(env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController

  def index
    @testimonials = Testimonial.all
  end

  def find_guest
    result = { status: true, error: nil }

    begin
      result[:data] = Guest.find_by_name(params[:name])
    rescue StandardError => e
      result[:status] = false
      result[:error] = e
    end

    render json: result
  end

  def confirm_guest
    result = { status: true, error: nil }

    begin
      Guest.update(params[:guest_id], { is_confirmed: true, confirmed_accompanying_number: params[:accompanying_number] })
      result[:data] = params
    rescue StandardError => e
      result[:status] = false
      result[:error] = e
    end

    render json: result
  end

  def autocomplete
    @guests_names = Guest.order(:name).where('upper(name) like ?', "%#{params[:term].upcase}%")
    respond_to do |format|
      format.html
      format.json {
        render json: @guests_names.map(&:name)
      }
    end
  end

  def new_testimonial
    @testimonial = Testimonial.new

    render partial: 'layouts/add_testimonial_form', :layout => false
  end

  def create_testimonial(isFacebook = false)
    result = { status: true, error: nil }

    begin
      user = User.find_by(id: session[:user_id]) if isFacebook
      testimonial = Testimonial.new
      testimonial.name = isFacebook ? user.name : params[:name]
      testimonial.testimonial = params[:testimonial]
      testimonial.provider = isFacebook ? user.provider : 'none'
      testimonial.picture = isFacebook ? user.picture : view_context.image_path('face.png')
      testimonial.profile = isFacebook ? user.profile_link : 'none'
      testimonial.save
      result[:data] = testimonial
    rescue StandardError => e
      result[:status] = false
      result[:error] = e
    end

    render json: result
  end

  def testimonial_user
    user = User.from_omniauth(env['omniauth.auth'])
    session[:user_id] = user.id
    create_testimonial(true)
  end

  def save_testimonial

  end
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  before_action :set_testimonial, only: [:show, :edit, :update, :destroy]
  before_action :can_go, only: [:index, :edit, :update, :destroy]

  # GET /testimonials
  # GET /testimonials.json
  def index
    @testimonials = Testimonial.all
  end

  # GET /testimonials/1
  # GET /testimonials/1.json
  def show
  end

  # GET /testimonials/new
  def new
    @testimonial = Testimonial.new
  end

  # GET /testimonials/1/edit
  def edit
  end

  # POST /testimonials
  # POST /testimonials.json
  def create
    @testimonial = Testimonial.new(testimonial_params)

    respond_to do |format|
      if @testimonial.save
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully created.' }
        format.json { render :show, status: :created, location: @testimonial }
      else
        format.html { render :new }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testimonials/1
  # PATCH/PUT /testimonials/1.json
  def update
    respond_to do |format|
      if @testimonial.update(testimonial_params)
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully updated.' }
        format.json { render :show, status: :ok, location: @testimonial }
      else
        format.html { render :edit }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testimonials/1
  # DELETE /testimonials/1.json
  def destroy
    @testimonial.destroy
    respond_to do |format|
      format.html { redirect_to testimonials_url, notice: 'Testimonial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testimonial
      @testimonial = Testimonial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testimonial_params
      params.require(:testimonial).permit(:name, :testimonial, :provider, :picture)
    end

  def can_go
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/layouts/_add_testimonial.html.erb
<a id="lightbox_link" class="dead_link" href="javascript:e.preventDefault()">
    <div class="testimonial_add_button">
        <%= image_tag(image_url 'add-testimonial-button.png') %>
        <p>Enviar depoimento</p>
    </div>
</a>

app/views/layouts/_add_testimonial_form.html.erb
<div class="col-sm-12 contact-form">
    <%= form_tag do %>
        <div class="form-group">
            <%= label_tag :testimonial, 'Mensagem', class: 'sr-only' %>
            <%= text_area_tag :testimonial, nil, id: 'contact-message', class: 'contact-message', placeholder: 'Mensagem...' %>
        </div>

        <div id="author" class="form-group">
            <%= label_tag :name, 'Nome', class: 'sr-only' %>
            <%= text_field_tag :name, nil, id: 'contact-name', class: 'contact-name', placeholder: 'Nome do autor...' %>
        </div>

        <div class="error-message"></div>

        <%= button_tag 'Assinar', type: 'button', id: 'add-testimonial', class: 'btn', onclick: 'javascript:window.signAlone(event);' %>
        <%= button_tag 'Assinar com Facebook', type: 'button', id: 'add-testimonial-facebook', class: 'btn', onclick: 'javascript:window.signWithFacebook(event);' %>

        <div class="singAloneOption">Para assinar sem usar o Facebook <%= link_to 'clique aqui', 'javascript:window.goToSingAlone(event);' %>.</div>
        <div class="singFacebookOption">Para assinar usando o Facebook <%= link_to 'clique aqui', 'javascript:window.goToSingFacebook(event);' %>.</div>
    <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
    <div class="container">
        <div class="row">
            <div class="col-sm-7 footer-copyright">
                <p>&copy; 2015 - Developed by <%= link_to 'Diogo de Lima', 'https://br.linkedin.com/in/diogogama', target: '_blank' %><br>Todos os direitos reservados.</p>
            </div>
            <div class="col-sm-5 footer-social">
                <!--<a class="ultm ultm-facebook ultm-48 ultm-square ultm-gray-to-color" href=""></a>-->
                <!--<a class="ultm ultm-twitter ultm-48 ultm-square ultm-gray-to-color" href=""></a>-->
                <!--<a class="ultm ultm-google-plus-1 ultm-48 ultm-square ultm-gray-to-color" href=""></a>-->
                <!--<a class="ultm ultm-dribbble ultm-48 ultm-square ultm-gray-to-color" href=""></a>-->
                <!--<a class="ultm ultm-pinterest ultm-48 ultm-square ultm-gray-to-color" href=""></a>-->
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_lightbox.html.erb
<div id="lightbox" class="containeccr">
    <div class="box">
        <a id="lightbox_link_close" class="lightbox_close" href="#">X</a>
        <p class="title">Criando depoimento</p>
        <div class="row lightbox_content">
            <!-- Conteúdo da lightbox -->
        </div>
    </div>
</div>

app/views/layouts/_nav.html.erb
<nav>
    <a class="menu-top" href="">Topo</a>
    <a class="menu-testimonials" href="">Depoimentos</a>
    <a class="menu-gift" href="">Lista de presentes</a>
    <a class="menu-confirmation" href="">Confirmação</a>
    <a class="menu-about-us" href="">Nossa história</a>
    <a class="menu-contact" href="">Local</a>
    <div class="hide-menu">
        <a href="" rel="tooltip" data-placement="bottom" data-original-title="Ocultar menu">
            <i class="fa fa-bars"></i>
        </a>
    </div>
</nav>

<div class="show-menu">
    <a href="" rel="tooltip" data-placement="bottom" data-original-title="Exibir menu">
        <i class="fa fa-bars"></i>
    </a>
</div>

app/views/layouts/application.html.erb
<!----------------------------------------------
                  _______   _______
                 /  __   | |   __  \
                /  /  |__| |__|  \  \
               /  /               \  \
              /  /                 \  \
              \  \                 /  /
               \  \    __   __    /  /
                \  \__|  | |  |__/  /
                 \_______| |_______/
       __                  __      __
     ||  \\  [] ||    [] ||  \\  ||   \\      //
     ||   \\ || ||    || ||   \\ ||__  \\    //
     ||   // || ||    || ||   // ||     \\  //
     ||__//  || ||___ || ||__//  ||__    \\//

----------------------------------------------->
<!DOCTYPE html>
<html lang="pt">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <%= csrf_meta_tags %>

        <title>♥ Maiara & Diogo ♥</title>

        <!-- CSS -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Rouge+Script" type="text/css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,100italic,300italic,400italic,700,700italic">
        <%= stylesheet_link_tag    'application', media: 'screen, projection', 'data-turbolinks-track' => true %>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the pae via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Favicon and touch icons -->
        <%= favicon_link_tag image_url('favicon.ico') %>
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<%= asset_path 'apple-touch-icon-144-precomposed.png' %>">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<%= asset_path 'apple-touch-icon-114-precomposed.png' %>">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<%= asset_path 'apple-touch-icon-72-precomposed.png' %>">
        <link rel="apple-touch-icon-precomposed" href="<%= asset_path 'apple-touch-icon-57-precomposed.png' %>">
    </head>

    <body>
        <% if current_page?('/') %>
            <!-- Load screen -->
            <div id="loader-wrapper">
                <div id="loader"></div>
            </div>
        <% end %>

        <!-- Top menu -->
        <%= render 'layouts/nav' %>

        <!-- Page content -->
        <%= yield %>

        <!-- Lightbox and testimonial add button -->
        <%= render 'layouts/add_testimonial' %>
        <%= render 'layouts/lightbox' %>

        <!-- Page footer -->
        <%= render 'layouts/footer' %>

        <!-- Javascript -->
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    </body>
</html>

app/views/static_page/_about_us.html.erb
<div class="about-us whos-behind-container">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 whos-behind">
                <h3>Uma breve história</h3>
                <!--<br /><br />-->
                <%#= video_tag '395967764.mp4', width: '100%', :controls => true %>
                <iframe id="our-video" src="https://player.vimeo.com/video/134247752?title=0&byline=0&portrait=0" width="100%" height="80%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
            </div>
        </div>
    </div>
</div>

app/views/static_page/_confirmation.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-12 subscribe confirmation">
            <h3>Confirmação de presença</h3>
            <p>Insira no campo abaixo seu nome conforme impresso no convite:</p>

            <%= form_tag(nil, id: 'check-name', class: 'form-inline') do %>
                <div class="form-group">
                    <%= text_field_tag :name, params[:name], id: 'confirmation-name', placeholder: 'Nome no convite...' %>
                </div>
                <%= button_tag 'Buscar', type: 'submit', id: 'find-guest', class: 'btn' %>
            <% end %>

            <%= form_tag(nil, id: 'confirm-name', class: 'form-inline') do %>
                <%= hidden_field_tag :guest_id %>
                <div class="form-group">
                    <div class="form-row">
                        <%= label_tag :confirmation_name, 'Nome', class: 'confirm-info' %>
                        <%= text_field_tag :confirmation_name, nil, class: 'confirmation-name', readonly: true %>
                    </div>

                    <div class="form-row">
                        <%= label_tag :accompanying_number, 'Nº de acompanhantes', class: 'confirm-info' %>
                        <%= text_field_tag :accompanying_number, nil, class: 'accompanying_number', type: 'number' %>
                        <%= button_tag 'Confirmar', type: 'submit', id: 'confirm-guest', class: 'btn' %>
                    </div>
                </div>
            <% end %>

            <div class="success-message"></div>
            <div class="error-message"></div>
            <div class="warn-message"></div>
        </div>
    </div>
</div>

app/views/static_page/_gift_list.html.erb
<div class="gift-section">
    <div class="container">
        <div class="embed-container">
            <object id="presents-embed" data="http://www.pontofrio.com.br/Site/ListaGerenciadaLandingPage.aspx?idListaCompra=422549" width="100%">
                <p class="iframe_erro">Puts, foi mal parece que a lista não carregou!!! Se você estiver acessando através de qualquer dispositivo movél como celular ou tablet
                    já vou avisando que a culpa não e minha, infelizmente o Ponto Frio não libera o acesso da lista de presentes para dispositiveis móveis,
                    afinal, quem usa celular pra navegar na net hoje em dia?! Outra possibilidade é você estar em um navegador que não suporta IFRAMES, ou seja
                    lá o que isso for rsrsrsrs, enfim, se você estiver em um celular terá de ir a um computador (sim eu sei não faz sentido!) caso esteja em um
                    computador que não suporte esta avançadíssima tecnologia chamada IFRAME
                    <%= link_to 'clique aqui', 'http://www.pontofrio.com.br/Site/ListaGerenciadaLandingPage.aspx?idListaCompra=422549', target: '_blank' %>
                    e você vai conseguir acessar a lista de presentes diretamento do site do Ponto Frio.
                </p>
            </object>
        </div>
    </div>
</div>

app/views/static_page/_home.html.erb
<div class="home-section">
    <div class="inner-bg">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="logo">
                        <h1><%= content_tag 'a', 'Maiara & Diogo' %></h1>
                    </div>

                    <h2 class="our-name">Maiara & Diogo</h2>
                    <p>Já estamos em contagem regressiva para o grande dia. Faltam...</p>

                    <div class="timer">
                        <div class="days-wrapper">
                            <span class="days"></span> <br>dias
                        </div>
                        <div class="hours-wrapper">
                            <span class="hours"></span> <br>horas
                        </div>
                        <div class="minutes-wrapper">
                            <span class="minutes"></span> <br>minutos
                        </div>
                        <div class="seconds-wrapper">
                            <span class="seconds"></span> <br>segundos
                        </div>
                    </div>

                    <p class="top-arrow">
                        <i class="fa fa-chevron-down"></i>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/static_page/_location.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-12 contact">
            <h3>Local da cerimônia</h3>
            <br />
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d29468.900820764084!2d-43.16218943498074!3d-22.593588036191818!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0000000000000000%3A0x79137728d1a16e0a!2sIgreja+Nossa+Senhora+Aparecida!5e0!3m2!1spt-BR!2sbr!4v1437972651268" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
    </div>
</div>

app/views/static_page/_testimonials.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-12 testimonials">
            <h3>Declarações de amizade!</h3>
            <div class="testimonial-active"></div>
            <% if @testimonials && @testimonials.size > 0 %>
                <div id="t-like" class="fb-like bottom20" data-href="<%= "#{request.original_url[0...-1]}/testimonials/#{@testimonials[0].id}" %>" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false"></div>
            <% end %>
            <div class="testimonial-quote">&ldquo; &rdquo;</div>

            <% Array.wrap(@testimonials).each do |testimonial| %>
                <div class="testimonial-single">
                    <p>
                        <%= testimonial.testimonial %>
                        <br />
                        <a href="<%= testimonial.profile %>"><%= testimonial.name %></a>
                    </p>
                    <div class='testimonial-single-image'>
                        <img src="<%= testimonial.picture %>" alt="" data-id="<%= testimonial.id %>" onclick="javascript:showSelectedTestimonial(event, this)">
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/static_page/index.html.erb
<!-- Home -->
<%= render 'static_page/home' %>

<!-- Testimonials -->
<%= render 'static_page/testimonials' %>

<!-- Gifts List -->
<%= render 'static_page/gift_list' %>

<!-- Confirmation -->
<%= render 'static_page/confirmation' %>

<!-- Our History -->
<%= render 'static_page/about_us' %>

<!-- Location -->
<%= render 'static_page/location' %>

app/views/testimonials/_form.html.erb
<%= form_for(@testimonial) do |f| %>
  <% if @testimonial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testimonial.errors.count, "error") %> prohibited this testimonial from being saved:</h2>

      <ul>
      <% @testimonial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :testimonial %><br>
    <%= f.text_area :testimonial %>
  </div>
  <div class="field">
    <%= f.label :provider %><br>
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/testimonials/edit.html.erb
<h1>Editing Testimonial</h1>

<%= render 'form' %>

<%= link_to 'Show', @testimonial %> |
<%= link_to 'Back', testimonials_path %>

app/views/testimonials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Testimonials</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Testimonial</th>
      <th>Provider</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @testimonials.each do |testimonial| %>
      <tr>
        <td><%= testimonial.name %></td>
        <td><%= testimonial.testimonial %></td>
        <td><%= testimonial.provider %></td>
        <td><%= testimonial.picture %></td>
        <td><%= link_to 'Show', testimonial %></td>
        <td><%= link_to 'Edit', edit_testimonial_path(testimonial) %></td>
        <td><%= link_to 'Destroy', testimonial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Testimonial', new_testimonial_path %>

app/views/testimonials/new.html.erb
<h1>New Testimonial</h1>

<%= render 'form' %>

<%= link_to 'Back', testimonials_path %>

app/views/testimonials/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-12 testimonials">
            <h3>Declarações de amizade!</h3>
            <div class="testimonial-active"></div>
            <div class="testimonial-quote">&ldquo; &rdquo;</div>

            <div class="testimonial-single">
                <p>
                    <%= @testimonial.testimonial %>
                    <br />
                    <a href="<%= @testimonial.profile %>"><%= @testimonial.name %></a>
                </p>
                <div class='testimonial-single-image'>
                    <img src="<%= @testimonial.picture %>" alt="">
                </div>
            </div>
        </div>
    </div>
</div>

<%#= link_to 'Edit', edit_testimonial_path(@testimonial) %> |
<%#= link_to 'Back', testimonials_path %>